info:
    description: JSON/HTTP API exposed by the Veilgate admin server for operators and automation.
    title: Veilgate Admin API
    version: 0.2.8
openapi: 3.0.0
paths:
    /admin/auth/login:
        post:
            description: Authenticates an admin user and establishes a session via an HTTP-only cookie.
            operationId: postAdminAuthLogin
            responses:
                "200":
                    description: Successful response.
            summary: Admin login
            tags:
                - admin
                - auth
    /admin/auth/logout:
        post:
            description: Terminates the current admin session by clearing the session cookie.
            operationId: postAdminAuthLogout
            responses:
                "200":
                    description: Successful response.
            summary: Admin logout
            tags:
                - admin
                - auth
    /admin/mcp/tools:
        get:
            description: Returns MCP tools and their mappings, once MCP configuration is wired.
            operationId: getAdminMCPTools
            responses:
                "200":
                    description: Successful response.
            summary: List MCP tools
            tags:
                - admin
                - mcp
    /admin/policies:
        get:
            description: Returns auth and rate-limit policies configured for the gateway.
            operationId: getAdminPolicies
            responses:
                "200":
                    description: Successful response.
            summary: List policies
            tags:
                - admin
    /admin/routes:
        get:
            description: Returns the effective route configuration, including upstream associations and attached policies.
            operationId: getAdminRoutes
            responses:
                "200":
                    description: Successful response.
            summary: List routes
            tags:
                - admin
        post:
            description: Creates a new route and applies the updated configuration at runtime.
            operationId: postAdminRoutes
            responses:
                "200":
                    description: Successful response.
            summary: Create route
            tags:
                - admin
    /admin/routes/{id}:
        delete:
            description: Deletes an existing route identified by ID and applies the updated configuration at runtime.
            operationId: deleteAdminRoute
            responses:
                "200":
                    description: Successful response.
            summary: Delete route
            tags:
                - admin
        put:
            description: Updates an existing route identified by ID and applies the updated configuration at runtime.
            operationId: putAdminRoute
            responses:
                "200":
                    description: Successful response.
            summary: Update route
            tags:
                - admin
    /admin/security/api-keys:
        get:
            description: Returns API keys managed via the admin API, including basic metadata.
            operationId: getAdminAPIKeys
            responses:
                "200":
                    description: Successful response.
            summary: List API keys
            tags:
                - admin
                - security
        post:
            description: Generates a new API key, returns it once, and applies it to the running configuration.
            operationId: postAdminAPIKeys
            responses:
                "200":
                    description: Successful response.
            summary: Create API key
            tags:
                - admin
                - security
    /admin/security/api-keys/{id}:
        delete:
            description: Deletes an existing API key identified by ID from the running configuration.
            operationId: deleteAdminAPIKey
            responses:
                "200":
                    description: Successful response.
            summary: Delete API key
            tags:
                - admin
                - security
        put:
            description: Updates metadata or active status of an existing API key identified by ID.
            operationId: putAdminAPIKey
            responses:
                "200":
                    description: Successful response.
            summary: Update API key
            tags:
                - admin
                - security
    /admin/stats/api-keys:
        get:
            description: Returns basic usage statistics per API key, such as request counts and latency.
            operationId: getAdminAPIKeyStats
            responses:
                "200":
                    description: Successful response.
            summary: API key stats
            tags:
                - admin
                - stats
                - security
    /admin/stats/routes:
        get:
            description: Returns basic usage statistics per route, such as request counts and latency.
            operationId: getAdminRouteStats
            responses:
                "200":
                    description: Successful response.
            summary: Route stats
            tags:
                - admin
                - stats
    /admin/summary:
        get:
            description: Returns basic summary statistics such as total routes and upstreams.
            operationId: getAdminSummary
            responses:
                "200":
                    description: Successful response.
            summary: Gateway summary
            tags:
                - admin
    /admin/upstreams:
        get:
            description: Returns upstream pools and their endpoints, including basic health information.
            operationId: getAdminUpstreams
            responses:
                "200":
                    description: Successful response.
            summary: List upstreams
            tags:
                - admin
        post:
            description: Creates a new upstream pool with endpoints and applies the updated configuration at runtime.
            operationId: postAdminUpstreams
            responses:
                "200":
                    description: Successful response.
            summary: Create upstream
            tags:
                - admin
    /admin/upstreams/{id}:
        delete:
            description: Deletes an upstream pool identified by ID and applies the updated configuration at runtime.
            operationId: deleteAdminUpstream
            responses:
                "200":
                    description: Successful response.
            summary: Delete upstream
            tags:
                - admin
        put:
            description: Updates endpoints of an existing upstream pool identified by ID and applies the updated configuration at runtime.
            operationId: putAdminUpstream
            responses:
                "200":
                    description: Successful response.
            summary: Update upstream
            tags:
                - admin
    /healthz:
        get:
            description: Basic liveness endpoint used by orchestration systems to check that Veilgate is running.
            operationId: getHealthz
            responses:
                "200":
                    description: Successful response.
            summary: Liveness probe
            tags:
                - health
    /metrics:
        get:
            description: Exposes Prometheus-compatible metrics describing gateway and upstream behavior.
            operationId: getMetrics
            responses:
                "200":
                    description: Successful response.
            summary: Prometheus metrics
            tags:
                - metrics
    /readyz:
        get:
            description: Readiness endpoint indicating whether Veilgate has loaded configuration and is ready to serve traffic.
            operationId: getReadyz
            responses:
                "200":
                    description: Successful response.
            summary: Readiness probe
            tags:
                - health
